[package]
name = "chv-bitmap-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.7.0"
rand = "0.9.2"
itertools = "0.14.0"

[dev-dependencies]
proptest = "1.9.0"

[[bench]]
name = "bench"
harness = false
